export const candidates =[
 {
id: 521,
committee_id: "20175033290",
last_name: "Coffman",
full_name: "Cynthia Coffman",
candidate_id: "20175033289",
committee_name: "Cynthia Coffman for Governor",
party: "Republican",
active: true,
website: "http://cynthia2018.com/",
image: "http://msantray.fatcow.com/governor_photos/cynthia_coffmann.jpg"
},
{id: 528,
committee_id: "20175032028",
last_name: "Kennedy",
full_name: "Cary Kennedy",
candidate_id: "20175032046",
committee_name: "Cary Kennedy For Governor",
party: "Democrat",
active: true,
website: "http://carykennedyforgovernor.com/",
image: "http://msantray.fatcow.com/governor_photos/cary_kennedy.jpeg"}
]

export const candidateTotals = [
{id: 35,
candidateId: "20175032139",
name: "Jared Polis",
party: "Democrat",
expenditureTotal: 1146046.36,
contributionTotal: 1534817.33,
contributionNum: 4456,
avgContribution: 344.44,
active: "true",
image: "http://msantray.fatcow.com/governor_photos/jared_polis.jpg"},
{id: 25,
candidateId: "20175031889",
name: "Michael Johnston",
party: "Democrat",
expenditureTotal: 787783.35,
contributionTotal: 1520183.11,
contributionNum: 6794,
avgContribution: 223.75,
active: true,
image: "http://msantray.fatcow.com/governor_photos/michael_johnston.jpg"}
]

export const selectedCandidate = {
id: 44,
name: "Jim Rundberg",
lastName: "Rundberg",
image: "http://msantray.fatcow.com/governor_photos/jim_rundberg.jpg",
party: "Republican",
website: "",
active: "true",
committee: "Rundberg For Colorado Governor",
candidateId: "20135025390",
expenditureTotal: "0.00",
contributionTotal: "331.66",
contributionNum: 1,
avgContribution: "331.66",
contributions: [
{id: 531735,
committee_id: "20135025390",
committee_name: "RUNDBERG FOR COLORADO GOVERNOR",
contribution_amount: "331.66",
contribution_date: "2017-03-09T07:00:00.000Z",
donor_last: "RUNDBERG",
donor_first: "JIM",
donor_address: "56571 EWING RD",
donor_city: "MOFFAT",
donor_state: "CO",
donor_zip: "81143",
record_id: "4500073",
contribution_type: "Monetary (Itemized)",
donor_type: "Candidate",
committee_type: "Candidate Committee",
candidate_name: "JIM LENNART RUNDBERG",
donor_employer: "",
donor_occupation: "",
Jurisdiction: "STATEWIDE"}
]
}

export const contributions = [
{id: 531735,
committee_id: "20135025390",
committee_name: "RUNDBERG FOR COLORADO GOVERNOR",
contribution_amount: "331.66",
contribution_date: "2017-03-09T07:00:00.000Z",
donor_last: "RUNDBERG",
donor_first: "JIM",
donor_address: "56571 EWING RD",
donor_city: "MOFFAT",
donor_state: "CO",
donor_zip: "81143",
record_id: "4500073",
contribution_type: "Monetary (Itemized)",
donor_type: "Candidate",
committee_type: "Candidate Committee",
candidate_name: "JIM LENNART RUNDBERG",
donor_employer: "",
donor_occupation: "",
Jurisdiction: "STATEWIDE"}
]